[supervisord]
nodaemon=true
logfile=/tmp/virgozki/supervisord.log
pidfile=/tmp/virgozki/supervisord.pid
user=root

[program:xray]
command=/usr/local/bin/xray run -c /etc/xray/config.json
autostart=true
autorestart=true
stderr_logfile=/var/log/xray/error.log
stdout_logfile=/var/log/xray/access.log

[program:openresty]
command=/usr/local/openresty/bin/openresty -g "daemon off;" -c /etc/openresty/nginx.conf
autostart=true
autorestart=true
stderr_logfile=/var/log/nginx/error.log
stdout_logfile=/var/log/nginx/access.log

[program:envoy]
command=/usr/local/bin/envoy -c /etc/envoy/envoy.yaml
autostart=true
autorestart=true
stderr_logfile=/tmp/virgozki-logs/envoy_err.log
stdout_logfile=/tmp/virgozki-logs/envoy_out.log

[program:anti_ddos]
command=python3 /usr/local/bin/anti_ddos.py
autostart=true
autorestart=true
